const t = "tui testcode"
const dev2 = "tui code them dev2 ne"
const dev22 = "Tui code cn 2 ne"
const dev1 = "Tui code cn 1 ne tui o day lam them nhieu thu ne"
const dev222 = "ahjhj chuc nang tui code ne tui tui lam ne"
const dev2222 = "ahjhj tui lam them nua na"
const dev22222 = "ahjhj lại lam na âsassadasd"
const dev11 = "dev1 tesst stash l2"
